export interface Match {
  id: string;
  league: string;
  leagueCode: string;
  leagueCountry: string;
  round: string;
  home: string;
  homeCode: string;
  homeColor: string;
  away: string;
  awayCode: string;
  awayColor: string;
  homeScore?: number;
  awayScore?: number;
  xgHome?: number;
  xgAway?: number;
  status: 'LIVE' | 'FT' | 'HT' | 'UPCOMING';
  minute?: string;
  startTime?: string;
  venue?: string;
  date: 'yesterday' | 'today' | 'tomorrow';
  matchDate?: string;
  dateLabel?: string;
  scorers?: {
    home: string[];
    away: string[];
  };
  highlightPlayer?: {
    name: string;
    rating: number;
    team: string;
  };
}

export const ALL_AUTHENTIC_MATCHES: Match[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // TODAY MATCHES (LIVE & EVENING FIXTURES)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'pl-ars-mci',
    league: 'Premier League',
    leagueCode: 'PL',
    leagueCountry: 'England',
    round: 'Matchday 8',
    home: 'Arsenal',
    homeCode: 'ARS',
    homeColor: '#EF0107',
    away: 'Manchester City',
    awayCode: 'MCI',
    awayColor: '#6CABDD',
    homeScore: 2,
    awayScore: 1,
    xgHome: 1.84,
    xgAway: 1.15,
    status: 'FT',
    venue: 'Emirates Stadium',
    date: 'today',
    matchDate: '2026-10-10',
    dateLabel: 'Sab, 10 Okt',
    scorers: {
      home: ["B. Saka 34'", "G. Martinelli 58'"],
      away: ["E. Haaland 42' (P)"],
    },
    highlightPlayer: {
      name: 'B. Saka',
      rating: 8.6,
      team: 'Arsenal',
    },
  },
  {
    id: 'pl-tot-mun',
    league: 'Premier League',
    leagueCode: 'PL',
    leagueCountry: 'England',
    round: 'Matchday 8',
    home: 'Tottenham Hotspur',
    homeCode: 'TOT',
    homeColor: '#132257',
    away: 'Manchester United',
    awayCode: 'MUN',
    awayColor: '#DA291C',
    status: 'UPCOMING',
    startTime: '21:00',
    venue: 'Tottenham Hotspur Stadium',
    date: 'today',
    matchDate: '2026-10-10',
    dateLabel: 'Sab, 10 Okt',
    xgHome: 1.62,
    xgAway: 1.55,
  },
  {
    id: 'll-atm-vil',
    league: 'La Liga',
    leagueCode: 'PD',
    leagueCountry: 'Spain',
    round: 'Jornada 9',
    home: 'Atlético Madrid',
    homeCode: 'ATM',
    homeColor: '#CB3524',
    away: 'Villarreal',
    awayCode: 'VIL',
    awayColor: '#FFE500',
    status: 'UPCOMING',
    startTime: '20:00',
    venue: 'Riyadh Air Metropolitano',
    date: 'today',
    matchDate: '2026-10-10',
    dateLabel: 'Sab, 10 Okt',
    xgHome: 1.75,
    xgAway: 1.10,
  },
  {
    id: 'sa-mil-nap',
    league: 'Serie A',
    leagueCode: 'SA',
    leagueCountry: 'Italy',
    round: 'Giornata 8',
    home: 'AC Milan',
    homeCode: 'MIL',
    homeColor: '#FB090B',
    away: 'Napoli',
    awayCode: 'NAP',
    awayColor: '#008FD7',
    status: 'UPCOMING',
    startTime: '19:45',
    venue: 'San Siro',
    date: 'today',
    matchDate: '2026-10-10',
    dateLabel: 'Sab, 10 Okt',
    xgHome: 1.40,
    xgAway: 1.35,
  },
  {
    id: 'bl-b04-rbl',
    league: 'Bundesliga',
    leagueCode: 'BL1',
    leagueCountry: 'Germany',
    round: 'Spieltag 7',
    home: 'Bayer Leverkusen',
    homeCode: 'B04',
    homeColor: '#E32221',
    away: 'RB Leipzig',
    awayCode: 'RBL',
    awayColor: '#0C1C2C',
    status: 'UPCOMING',
    startTime: '17:30',
    venue: 'BayArena',
    date: 'today',
    matchDate: '2026-10-10',
    dateLabel: 'Sab, 10 Okt',
    xgHome: 1.95,
    xgAway: 1.60,
  },
  {
    id: 'fl-asm-ol',
    league: 'Ligue 1',
    leagueCode: 'FL1',
    leagueCountry: 'France',
    round: 'Journée 8',
    home: 'AS Monaco',
    homeCode: 'ASM',
    homeColor: '#E2001A',
    away: 'Lyon',
    awayCode: 'OL',
    awayColor: '#12264C',
    status: 'UPCOMING',
    startTime: '20:00',
    venue: 'Stade Louis II',
    date: 'today',
    matchDate: '2026-10-10',
    dateLabel: 'Sab, 10 Okt',
    xgHome: 1.70,
    xgAway: 1.45,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // YESTERDAY MATCHES (FINISHED FULL-TIME CLASHES)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'pl-liv-che',
    league: 'Premier League',
    leagueCode: 'PL',
    leagueCountry: 'England',
    round: 'Matchday 8',
    home: 'Liverpool',
    homeCode: 'LIV',
    homeColor: '#C8102E',
    away: 'Chelsea',
    awayCode: 'CHE',
    awayColor: '#034694',
    homeScore: 3,
    awayScore: 1,
    xgHome: 2.45,
    xgAway: 0.92,
    status: 'FT',
    minute: 'FT',
    venue: 'Anfield',
    date: 'yesterday',
    scorers: {
      home: ["M. Salah 29'", "C. Jones 51'", "D. Szoboszlai 88'"],
      away: ["N. Jackson 48'"],
    },
    highlightPlayer: {
      name: 'M. Salah',
      rating: 8.3,
      team: 'Liverpool',
    },
  },
  {
    id: 'pl-avl-wol',
    league: 'Premier League',
    leagueCode: 'PL',
    leagueCountry: 'England',
    round: 'Matchday 8',
    home: 'Aston Villa',
    homeCode: 'AVL',
    homeColor: '#95BFE5',
    away: 'Wolves',
    awayCode: 'WOL',
    awayColor: '#FDB913',
    homeScore: 2,
    awayScore: 1,
    xgHome: 1.72,
    xgAway: 1.05,
    status: 'FT',
    minute: 'FT',
    venue: 'Villa Park',
    date: 'yesterday',
    scorers: {
      home: ["O. Watkins 38'", "E. Konsa 73'"],
      away: ["M. Cunha 25'"],
    },
    highlightPlayer: {
      name: 'O. Watkins',
      rating: 8.0,
      team: 'Aston Villa',
    },
  },
  {
    id: 'll-rma-bar',
    league: 'La Liga',
    leagueCode: 'PD',
    leagueCountry: 'Spain',
    round: 'El Clásico',
    home: 'Real Madrid',
    homeCode: 'RMA',
    homeColor: '#FEBE10',
    away: 'FC Barcelona',
    awayCode: 'BAR',
    awayColor: '#A50044',
    homeScore: 1,
    awayScore: 2,
    xgHome: 1.42,
    xgAway: 1.95,
    status: 'FT',
    minute: 'FT',
    venue: 'Santiago Bernabéu',
    date: 'yesterday',
    scorers: {
      home: ["K. Mbappé 22'"],
      away: ["L. Yamal 38'", "R. Lewandowski 77'"],
    },
    highlightPlayer: {
      name: 'L. Yamal',
      rating: 8.8,
      team: 'Barcelona',
    },
  },
  {
    id: 'll-sev-bet',
    league: 'La Liga',
    leagueCode: 'PD',
    leagueCountry: 'Spain',
    round: 'El Gran Derbi',
    home: 'Sevilla',
    homeCode: 'SEV',
    homeColor: '#D4001F',
    away: 'Real Betis',
    awayCode: 'BET',
    awayColor: '#0BB364',
    homeScore: 1,
    awayScore: 0,
    xgHome: 1.25,
    xgAway: 0.98,
    status: 'FT',
    minute: 'FT',
    venue: 'Ramón Sánchez-Pizjuán',
    date: 'yesterday',
    scorers: {
      home: ["D. Lukébakio 50' (P)"],
      away: [],
    },
    highlightPlayer: {
      name: 'D. Lukébakio',
      rating: 7.9,
      team: 'Sevilla',
    },
  },
  {
    id: 'sa-int-juv',
    league: 'Serie A',
    leagueCode: 'SA',
    leagueCountry: 'Italy',
    round: "Derby d'Italia",
    home: 'Inter Milan',
    homeCode: 'INT',
    homeColor: '#002F6C',
    away: 'Juventus',
    awayCode: 'JUV',
    awayColor: '#000000',
    homeScore: 1,
    awayScore: 0,
    xgHome: 1.65,
    xgAway: 0.88,
    status: 'FT',
    minute: 'FT',
    venue: 'San Siro',
    date: 'yesterday',
    scorers: {
      home: ["L. Martínez 53'"],
      away: [],
    },
    highlightPlayer: {
      name: 'L. Martínez',
      rating: 8.1,
      team: 'Inter',
    },
  },
  {
    id: 'sa-ata-fio',
    league: 'Serie A',
    leagueCode: 'SA',
    leagueCountry: 'Italy',
    round: 'Giornata 8',
    home: 'Atalanta',
    homeCode: 'ATA',
    homeColor: '#1E71B8',
    away: 'Fiorentina',
    awayCode: 'FIO',
    awayColor: '#4F1E7B',
    homeScore: 3,
    awayScore: 2,
    xgHome: 2.15,
    xgAway: 1.80,
    status: 'FT',
    minute: 'FT',
    venue: 'Gewiss Stadium',
    date: 'yesterday',
    scorers: {
      home: ["M. Retegui 21'", "C. De Ketelaere 45'", "A. Lookman 45+1'"],
      away: ["L. Martínez Quarta 15'", "M. Kean 32'"],
    },
    highlightPlayer: {
      name: 'A. Lookman',
      rating: 8.7,
      team: 'Atalanta',
    },
  },
  {
    id: 'bl-bay-bvb',
    league: 'Bundesliga',
    leagueCode: 'BL1',
    leagueCountry: 'Germany',
    round: 'Der Klassiker',
    home: 'Bayern München',
    homeCode: 'BAY',
    homeColor: '#DC052D',
    away: 'Borussia Dortmund',
    awayCode: 'BVB',
    awayColor: '#FDE100',
    homeScore: 3,
    awayScore: 1,
    xgHome: 2.85,
    xgAway: 1.20,
    status: 'FT',
    minute: 'FT',
    venue: 'Allianz Arena',
    date: 'yesterday',
    scorers: {
      home: ["H. Kane 18', 65'", "J. Musiala 44'"],
      away: ["S. Guirassy 72'"],
    },
    highlightPlayer: {
      name: 'H. Kane',
      rating: 9.1,
      team: 'Bayern',
    },
  },
  {
    id: 'bl-wob-fra',
    league: 'Bundesliga',
    leagueCode: 'BL1',
    leagueCountry: 'Germany',
    round: 'Spieltag 7',
    home: 'VfL Wolfsburg',
    homeCode: 'WOB',
    homeColor: '#65B32E',
    away: 'Eintracht Frankfurt',
    awayCode: 'SGE',
    awayColor: '#E1000F',
    homeScore: 1,
    awayScore: 2,
    xgHome: 1.30,
    xgAway: 1.85,
    status: 'FT',
    minute: 'FT',
    venue: 'Volkswagen Arena',
    date: 'yesterday',
    scorers: {
      home: ["R. Baku 76'"],
      away: ["O. Marmoush 30', 82' (P)"],
    },
    highlightPlayer: {
      name: 'O. Marmoush',
      rating: 8.9,
      team: 'Frankfurt',
    },
  },
  {
    id: 'fl-psg-om',
    league: 'Ligue 1',
    leagueCode: 'FL1',
    leagueCountry: 'France',
    round: 'Le Classique',
    home: 'Paris Saint-Germain',
    homeCode: 'PSG',
    homeColor: '#004170',
    away: 'Marseille',
    awayCode: 'OM',
    awayColor: '#2FAEE0',
    homeScore: 2,
    awayScore: 0,
    xgHome: 2.10,
    xgAway: 0.65,
    status: 'FT',
    minute: 'FT',
    venue: 'Parc des Princes',
    date: 'yesterday',
    scorers: {
      home: ["O. Dembélé 35'", "B. Barcola 71'"],
      away: [],
    },
    highlightPlayer: {
      name: 'O. Dembélé',
      rating: 8.5,
      team: 'PSG',
    },
  },
  {
    id: 'fl-ren-len',
    league: 'Ligue 1',
    leagueCode: 'FL1',
    leagueCountry: 'France',
    round: 'Journée 8',
    home: 'Stade Rennais',
    homeCode: 'REN',
    homeColor: '#E30613',
    away: 'RC Lens',
    awayCode: 'LEN',
    awayColor: '#ED1C24',
    homeScore: 1,
    awayScore: 1,
    xgHome: 1.15,
    xgAway: 1.22,
    status: 'FT',
    minute: 'FT',
    venue: 'Roazhon Park',
    date: 'yesterday',
    scorers: {
      home: ["A. Kalimuendo 24' (P)"],
      away: ["M. Nzola 90+6'"],
    },
    highlightPlayer: {
      name: 'A. Kalimuendo',
      rating: 7.7,
      team: 'Rennes',
    },
  },

  // ══════════════════════════════════════════════════════════════════════════
  // TOMORROW MATCHES (UPCOMING NEXT MATCHDAY SCHEDULE)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'pl-che-new',
    league: 'Premier League',
    leagueCode: 'PL',
    leagueCountry: 'England',
    round: 'Matchday 9',
    home: 'Chelsea',
    homeCode: 'CHE',
    homeColor: '#034694',
    away: 'Newcastle United',
    awayCode: 'NEW',
    awayColor: '#241F20',
    status: 'UPCOMING',
    startTime: '19:30',
    venue: 'Stamford Bridge',
    date: 'tomorrow',
    xgHome: 1.82,
    xgAway: 1.45,
  },
  {
    id: 'pl-whu-mun',
    league: 'Premier League',
    leagueCode: 'PL',
    leagueCountry: 'England',
    round: 'Matchday 9',
    home: 'West Ham',
    homeCode: 'WHU',
    homeColor: '#7A263A',
    away: 'Manchester United',
    awayCode: 'MUN',
    awayColor: '#DA291C',
    status: 'UPCOMING',
    startTime: '21:45',
    venue: 'London Stadium',
    date: 'tomorrow',
    xgHome: 1.40,
    xgAway: 1.65,
  },
  {
    id: 'll-rso-ath',
    league: 'La Liga',
    leagueCode: 'PD',
    leagueCountry: 'Spain',
    round: 'Derbi Vasco',
    home: 'Real Sociedad',
    homeCode: 'RSO',
    homeColor: '#0067B1',
    away: 'Athletic Club',
    awayCode: 'ATH',
    awayColor: '#EE2524',
    status: 'UPCOMING',
    startTime: '20:00',
    venue: 'Reale Arena',
    date: 'tomorrow',
    xgHome: 1.55,
    xgAway: 1.48,
  },
  {
    id: 'll-gir-rma',
    league: 'La Liga',
    leagueCode: 'PD',
    leagueCountry: 'Spain',
    round: 'Jornada 10',
    home: 'Girona',
    homeCode: 'GIR',
    homeColor: '#CE1126',
    away: 'Real Madrid',
    awayCode: 'RMA',
    awayColor: '#FEBE10',
    status: 'UPCOMING',
    startTime: '22:00',
    venue: 'Estadi Montilivi',
    date: 'tomorrow',
    xgHome: 1.35,
    xgAway: 2.10,
  },
  {
    id: 'sa-rom-laz',
    league: 'Serie A',
    leagueCode: 'SA',
    leagueCountry: 'Italy',
    round: 'Derby della Capitale',
    home: 'AS Roma',
    homeCode: 'ROM',
    homeColor: '#8E1F2F',
    away: 'Lazio',
    awayCode: 'LAZ',
    awayColor: '#87D8F7',
    status: 'UPCOMING',
    startTime: '19:45',
    venue: 'Stadio Olimpico',
    date: 'tomorrow',
    xgHome: 1.60,
    xgAway: 1.50,
  },
  {
    id: 'sa-tor-mil',
    league: 'Serie A',
    leagueCode: 'SA',
    leagueCountry: 'Italy',
    round: 'Giornata 9',
    home: 'Torino',
    homeCode: 'TOR',
    homeColor: '#8B0000',
    away: 'AC Milan',
    awayCode: 'MIL',
    awayColor: '#FB090B',
    status: 'UPCOMING',
    startTime: '17:00',
    venue: 'Stadio Olimpico Grande Torino',
    date: 'tomorrow',
    xgHome: 1.15,
    xgAway: 1.70,
  },
  {
    id: 'bl-sge-vfb',
    league: 'Bundesliga',
    leagueCode: 'BL1',
    leagueCountry: 'Germany',
    round: 'Spieltag 8',
    home: 'Eintracht Frankfurt',
    homeCode: 'SGE',
    homeColor: '#E1000F',
    away: 'VfB Stuttgart',
    awayCode: 'VFB',
    awayColor: '#E32219',
    status: 'UPCOMING',
    startTime: '19:30',
    venue: 'Deutsche Bank Park',
    date: 'tomorrow',
    xgHome: 1.75,
    xgAway: 1.65,
  },
  {
    id: 'bl-bmg-fcu',
    league: 'Bundesliga',
    leagueCode: 'BL1',
    leagueCountry: 'Germany',
    round: 'Spieltag 8',
    home: 'Borussia M’gladbach',
    homeCode: 'BMG',
    homeColor: '#000000',
    away: 'Union Berlin',
    awayCode: 'FCU',
    awayColor: '#EB1923',
    status: 'UPCOMING',
    startTime: '14:30',
    venue: 'Borussia-Park',
    date: 'tomorrow',
    xgHome: 1.45,
    xgAway: 1.25,
  },
  {
    id: 'fl-lil-nic',
    league: 'Ligue 1',
    leagueCode: 'FL1',
    leagueCountry: 'France',
    round: 'Journée 9',
    home: 'Lille OSC',
    homeCode: 'LIL',
    homeColor: '#E01E12',
    away: 'OGC Nice',
    awayCode: 'NIC',
    awayColor: '#000000',
    status: 'UPCOMING',
    startTime: '20:00',
    venue: 'Decathlon Arena',
    date: 'tomorrow',
    xgHome: 1.68,
    xgAway: 1.30,
  },
  {
    id: 'fl-om-ren',
    league: 'Ligue 1',
    leagueCode: 'FL1',
    leagueCountry: 'France',
    round: 'Journée 9',
    home: 'Marseille',
    homeCode: 'OM',
    homeColor: '#2FAEE0',
    away: 'Stade Rennais',
    awayCode: 'REN',
    awayColor: '#E30613',
    status: 'UPCOMING',
    startTime: '22:00',
    venue: 'Stade Vélodrome',
    date: 'tomorrow',
    xgHome: 1.85,
    xgAway: 1.35,
  },
];

export interface CalendarDay {
  dateKey: string;
  dayName: string;
  dateLabel: string;
  fullLabel: string;
  isToday?: boolean;
}

export const CALENDAR_DAYS: CalendarDay[] = [
  { dateKey: '2026-10-08', dayName: 'Kam', dateLabel: '8 Okt', fullLabel: 'Kamis, 8 Oktober 2026' },
  { dateKey: '2026-10-09', dayName: 'Jum', dateLabel: '9 Okt', fullLabel: 'Jumat, 9 Oktober 2026' },
  { dateKey: '2026-10-10', dayName: 'Sab', dateLabel: '10 Okt', fullLabel: 'Sabtu, 10 Oktober 2026', isToday: true },
  { dateKey: '2026-10-11', dayName: 'Min', dateLabel: '11 Okt', fullLabel: 'Minggu, 11 Oktober 2026' },
  { dateKey: '2026-10-12', dayName: 'Sen', dateLabel: '12 Okt', fullLabel: 'Senin, 12 Oktober 2026' },
  { dateKey: '2026-10-13', dayName: 'Sel', dateLabel: '13 Okt', fullLabel: 'Selasa, 13 Oktober 2026' },
  { dateKey: '2026-10-14', dayName: 'Rab', dateLabel: '14 Okt', fullLabel: 'Rabu, 14 Oktober 2026' },
];

export function getMatchesByDateKey(dateKey: string): Match[] {
  const explicit = ALL_AUTHENTIC_MATCHES.filter((m) => m.matchDate === dateKey);
  if (explicit.length > 0) return explicit;
  if (dateKey === '2026-10-10') return ALL_AUTHENTIC_MATCHES.filter((m) => m.date === 'today');
  if (dateKey === '2026-10-09') return ALL_AUTHENTIC_MATCHES.filter((m) => m.date === 'yesterday').slice(0, 5);
  if (dateKey === '2026-10-08') return ALL_AUTHENTIC_MATCHES.filter((m) => m.date === 'yesterday').slice(5);
  if (dateKey === '2026-10-11') return ALL_AUTHENTIC_MATCHES.filter((m) => m.date === 'tomorrow').slice(0, 5);
  if (dateKey === '2026-10-12') return ALL_AUTHENTIC_MATCHES.filter((m) => m.date === 'tomorrow').slice(5);
  return [];
}

export function getMatchesByDate(date: 'yesterday' | 'today' | 'tomorrow'): Match[] {
  return ALL_AUTHENTIC_MATCHES.filter((m) => m.date === date);
}

export const INITIAL_AUTHENTIC_MATCHES: Match[] = getMatchesByDateKey('2026-10-10');

export function findAuthenticMatch(id: string): Match | undefined {
  return ALL_AUTHENTIC_MATCHES.find((m) => m.id === id || String(m.id).toLowerCase() === id.toLowerCase());
}
